version: "2.1"
services:
  students-ms:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      students-db:
        condition: service_healthy  
  students-db:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: students-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
